/* eslint-disable indent */
// convert es5 to es6 syntax :'/
// module.exports = {

export default {
       products: [
        {
           _id: 'qwertyuiop11',
           name: 'full zip running shirts',
           category: 'shirts',
           image: '../images/product-1.jpg',
           price: 55,
           brand: 'hiskywin',
           rating: 4.5,
           numReviews: 10,
           countInStock: 6,
        },
        {
            _id: 'qwertyuiop12',
            name: 't shirt 2',
            category: 'shirts',
            image: '../images/product-2.jpg',
            price: 70,
            brand: 'nike',
            rating: 4.5,
            numReviews: 6,
            countInStock: 0,
         },
         {
            _id: 'qwertyuiop13',
            name: 'shirt 3',
            category: 'shirts',
            image: '../images/product-3.jpg',
            price: 70,
            brand: 'addidas',
            rating: 3.5,
            numReviews: 10,
            countInStock: 7,
         },
         {
            _id: 'qwertyuiop14',
            name: 'shirts 4',
            category: 'shirts',
            image: '../images/product-4.jpg',
            price: 40,
            brand: 'hiskywin',
            rating: 1.5,
            numReviews: 10,
            countInStock: 2,
         },
         {
            _id: 'qwertyuiop15',
            name: ' shirts 5',
            category: 'shirts',
            image: '../images/product-5.jpg',
            price: 90,
            brand: 'hiskywin',
            rating: 5,
            numReviews: 9,
            countInStock: 4,
         },
         {
            _id: 'qwertyuiop16',
            name: ' shirts 6',
            category: 'shirts',
            image: '../images/product-6.jpg',
            price: 80,
            brand: 'nike',
            rating: 4,
            numReviews: 10,
            countInStock: 22,
         },
    ],
}
